<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config["protocol"]="smtp";
$config["smtp_host"]="ssl://smtp.googlemail.com";
$config["smtp_port"]="465";
$config["smtp_timeout"]="30";
$config["smtp_user"]="server@joomi.co.il";
$config["smtp_pass"]="0775177699";
$config["charset"]="utf-8";
$config['mailtype'] = "html";
$config["newline"]="\r\n"; 